# Generated by Django 6.0.3 on 2026-04-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_code', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.PositiveBigIntegerField()),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non-AC')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], max_length=20)),
                ('depot', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bus_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
