# Generated by Django 6.0.4 on 2026-04-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_code', models.CharField(max_length=10, unique=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity', models.PositiveBigIntegerField()),
                ('bus_type', models.CharField(choices=[('AC', 'AC'), ('NON_AC', 'Non-AC')], max_length=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('ON_ROUTE', 'On Route')], max_length=20)),
                ('depot', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bus_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor_name', models.CharField(max_length=100)),
                ('c_dob', models.DateField()),
                ('c_nic_number', models.CharField(max_length=20, unique=True)),
                ('c_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('c_phone_number', models.CharField(max_length=10)),
                ('c_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('conductor_address', models.TextField(blank=True, null=True)),
                ('conductor_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('conductor_registration_date', models.DateField()),
                ('conductor_id_image', models.ImageField(blank=True, null=True, upload_to='driver_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nic_number', models.CharField(max_length=20, unique=True)),
                ('driving_license_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driver_address', models.TextField(blank=True, null=True)),
                ('driver_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('driver_registration_date', models.DateField()),
                ('driver_id_image', models.ImageField(blank=True, null=True, upload_to='driver_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=10)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('estimated_duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('day_of_week', models.CharField(choices=[('daily', 'Daily'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='daily', max_length=10)),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], max_length=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conductor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed')], default='NOT STARTED', max_length=20)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('delay_reason', models.TextField(blank=True, null=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.schedule')),
            ],
        ),
    ]
