# Generated by Django 6.0.4 on 2026-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='t_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ONGOING', 'Ongoing'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20),
        ),
    ]
