# Generated by Django 6.0.4 on 2026-04-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nic_number', models.CharField(max_length=20, unique=True)),
                ('driving_license_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('driver_address', models.TextField(blank=True, null=True)),
                ('driver_status', models.CharField(choices=[('AVAIALABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('driver_registration_date', models.DateField()),
                ('driver_id_image', models.ImageField(blank=True, null=True, upload_to='driver_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
