# Generated by Django 6.0.4 on 2026-04-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trip_t_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='return_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_trip', to='core.trip'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND', 'Outbound'), ('RETURN', 'Return')], max_length=10),
        ),
    ]
