# Generated by Django 6.0.4 on 2026-04-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trip_return_trip_alter_timetable_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conductor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
    ]
