# Generated by Django 6.0.4 on 2026-04-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schedule_conductor_alter_schedule_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OFF_DUTY', 'Off Duty')], default='OFF_DUTY', max_length=20)),
                ('clock_in_time', models.DateTimeField(blank=True, null=True)),
                ('clock_out_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.conductor')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(
                condition=(
                    (
                        models.Q(driver__isnull=False, conductor__isnull=True)
                        | models.Q(driver__isnull=True, conductor__isnull=False)
                    )
                ),
                name='attendance_has_exactly_one_staff_member',
            ),
        ),
    ]
