# Generated by Django 6.0.4 on 2026-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_route_alter_driver_driver_status_schedule_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor_name', models.CharField(max_length=100)),
                ('c_dob', models.DateField()),
                ('c_nic_number', models.CharField(max_length=20, unique=True)),
                ('c_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('c_phone_number', models.CharField(max_length=10)),
                ('c_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('conductor_address', models.TextField(blank=True, null=True)),
                ('conductor_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('conductor_registration_date', models.DateField()),
                ('conductor_id_image', models.ImageField(blank=True, null=True, upload_to='driver_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
