# Generated by Django 6.0.4 on 2026-04-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='order',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='route',
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stop')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
