# Generated by Django 6.0.4 on 2026-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staffattendance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffattendance',
            name='attendance_has_exactly_one_staff_member',
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('driver__isnull', False), ('conductor__isnull', True)), models.Q(('driver__isnull', True), ('conductor__isnull', False)), _connector='OR'), name='attendance_has_exactly_one_staff_member'),
        ),
    ]
