# Generated by Django 6.0.4 on 2026-04-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_staffattendance_attendance_has_exactly_one_staff_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_fuel_liters',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='fuel_efficiency_km_per_liter',
            field=models.FloatField(default=4.0),
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('FILL', 'Filled'), ('BURN', 'Burned')], max_length=10)),
                ('amount_liters', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions', to='core.bus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
