# Generated by Django 6.0.4 on 2026-04-11 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bus_current_fuel_liters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(default=django.utils.timezone.now)),
                ('mileage', models.PositiveIntegerField(help_text='Current mileage at the time of service')),
                ('service_history', models.TextField(help_text='Summary of service history / issue reported')),
                ('maintenance_details', models.TextField(help_text='Maintenance work completed for this service')),
                ('next_service_due_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.bus')),
            ],
            options={
                'ordering': ['-service_date', '-created_at'],
            },
        ),
    ]
