# Generated by Django 6.0.4 on 2026-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_busmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_ROUTE', 'On Route'), ('OFF_DUTY', 'Off Duty')], default='OFF_DUTY', max_length=20),
        ),
    ]
