# Generated by Django 6.0.4 on 2026-04-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_schedule_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='milage',
            field=models.FloatField(default=0),
        ),
    ]
