# Generated by Django 6.0.4 on 2026-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_busmaintenance_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='actual_arrival_time',
            field=models.DateTimeField(
                blank=True,
                help_text='Actual arrival date and time recorded when the trip completes.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='trip',
            name='actual_departure_time',
            field=models.DateTimeField(
                blank=True,
                help_text='Actual departure date and time recorded when the trip starts.',
                null=True,
            ),
        ),
    ]