# Generated by Django 6.0.4 on 2026-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_trip_actual_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='delay_started_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the delay started.', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'On going'), ('DELAYED', 'Delayed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
