# Generated by Django 6.0.4 on 2026-04-18 04:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_busrefuellog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passengers', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_simulated', models.BooleanField(default=True, help_text='True if generated by automated passenger simulation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='core.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerBoardingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_order', models.PositiveIntegerField()),
                ('passengers_boarded', models.PositiveIntegerField(default=0)),
                ('passengers_alighted', models.PositiveIntegerField(default=0)),
                ('fare_per_passenger', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stop_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_passengers', models.PositiveIntegerField(default=0)),
                ('cumulative_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trip_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_logs', to='core.triprevenue')),
            ],
            options={
                'ordering': ['stop_order'],
            },
        ),
    ]
