# Generated by Django 6.0.4 on 2026-04-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_triprevenue_passengerboardinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fuel_capacity_liters',
            field=models.PositiveIntegerField(default=200, help_text='Maximum fuel tank capacity in liters'),
        ),
    ]
