# Generated by Django 6.0.4 on 2026-04-22 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_bus_fuel_capacity_liters'),
    ]

    operations = [
        migrations.AddField(
            model_name='busrefuellog',
            name='external_bus_code',
            field=models.CharField(blank=True, help_text="Bus code for buses from other depots (not in this depot's database)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='busrefuellog',
            name='is_external_bus',
            field=models.BooleanField(default=False, help_text='True if this refuel was for a bus from another depot'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Maintenance'), ('ON_ROUTE', 'On Route')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='busrefuellog',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refuel_logs', to='core.bus'),
        ),
    ]
